name: Deploy para Azure App Service

on:
  push:
    branches:
      - Master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Login no Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy para Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: nome-do-meu-app  # troque pelo nome do seu App Service
          slot-name: production
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: .

            # outros comandos de build/deploy
